services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: priority
      POSTGRES_PASSWORD: priority
      POSTGRES_DB: priority
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
